services:
  browser-extension:
    build: .
    command: npx webpack --watch --config webpack.dev.js
    image: screenly-browser-extension:latest
    volumes:
      - .:/app:delegated
      - /app/node_modules/  # exclude from volume mount; we want this inside the container
    environment:
      - JEKYLL_ENV=development
