blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Screenly/Browser-Extension/blob/master/README.md
    about: Check out our documentation before creating an issue