---
name: Build

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build and generate Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker compose build

      # This step should probably be rewritten
      - name: Generate
        run: |
          docker run \
            --rm \
            sce_webpack:latest \
            /bin/bash -c "npx webpack --config webpack.dev.js && npm run teamcity"


      - name: Generate
        run: |
          mkdir artifacts

          docker run \
            --rm \
            -v $(pwd)/artifacts:/app/artifacts:delegated \
            sce_webpack:latest \
            /bin/bash -c "npm run build && cd dist && zip -r ../artifacts/screenly-chrome-extension.zip *"
