---
name: Run ESLint and Prettier

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*.*

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build Docker images
        run: |
          docker compose build
      - name: Run ESLint
        run: |
          ./bin/run_eslint.sh

  run-prettier:
    runs-on: ubuntu-latest
    name: Run Prettier
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build Docker images
        run: |
          docker compose build
      - name: Run Prettier
        run: |
          MODE="check" ./bin/run_formatter.sh
