---
name: Run Unit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*.*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker compose build

      - name: Run Unit Tests
        run: |
          docker run \
            --rm \
            -v $(pwd):/app:delegated \
            -v /app/node_modules \
            sbe_webpack:latest \
            /bin/bash -c "npx webpack --config webpack.dev.js && npm run test"
